### ISSUE TITLE
Pi Zero W

### ISSUE THREAD

**Issue by Kavex** [pipaos/pipaos#1]
Hmm from what I can tell it doesn't want to work with the built in wifi adapter for PI Zero W. Am I missing something there?

**Comment by skarbat** [comment]
hi Kerrigan @Kavex , thanks for raising this.

The PiZeroW [should come](https://www.raspberrypi.org/blog/raspberry-pi-zero-w-joins-family/) with the same wireless chipset as the RPI3B.

Have you edited the file `/boot/interfaces.txt` to provide the correct wireless settings?
You can easily edit it by inserting the sdcard to a regular computer.

If that doesn't work, could you please send the output of `dmesg` ?

**Comment by Kavex** [comment]
Hmm I notice a lot of people have issues with the ZeroW so I think i'll look into myself if the chipset is already supported. I could have just messed something up. 

Thanks for the reply

**Comment by taxilly** [comment]
Currently dealing with the same issue: https://github.com/skarbat/pilove/issues/3

`dmesg` output: https://hastebin.com/xohenimebe.txt

Something in the dmesg I spotted that is the probable cause,
```
[    0.000000] Machine model: Raspberry Pi ? Rev 1.1
```
The ZeroW is not being properly recognized...
