### ISSUE TITLE
Fat16 on CM3

### ISSUE THREAD

**Issue by carlo-luzi** [pipaos/pipaos#2]
Hi,

I've noticed that Compute Module 3 won't boot from FAT16 partition like ones in PipaOS.

Re-format partition FAT32 and copy back boot files bypass the issue.

Thanks,

--
CL

**Comment by skarbat** [comment]
Was certainly a bug in [xsysroot](https://github.com/skarbat/xsysroot/commit/c1348f5c1941efea6c4727ab843da4bed1f026a7)

Next `pipaos-latest.img.gz` nightly build should be fat32: http://pipaos.mitako.eu/download/

Thanks for reporting this!

**Comment by skarbat** [comment]
That seems to be looking good now:

```
sysop@pipaos:~$ sudo parted /dev/mmcblk0 print
[sudo] password for sysop:
Model: SD SL08G (sd/mmc)
Disk /dev/mmcblk0: 7948MB
Sector size (logical/physical): 512B/512B
Partition Table: msdos
Disk Flags:

Number  Start   End     Size    Type     File system  Flags
 1      1049kB  120MB   118MB   primary  fat32        lba
 2      121MB   1940MB  1819MB  primary  ext4
```
